import { VehicleConfig, LevelConfig, GameSettings, KeyBindings } from '../types/game';

export const DEFAULT_KEYBINDINGS: KeyBindings = {
  forward: 'KeyW',
  backward: 'KeyS',
  steerLeft: 'KeyA',
  steerRight: 'KeyD',
  handbrake: 'Space',
  reset: 'KeyR',
  pause: 'KeyP',
  camera: 'KeyC',
  minimap: 'KeyM',
  gearUp: 'KeyE',
  gearDown: 'KeyQ',
  gearReverse: 'KeyG',
  gearNeutral: 'KeyN',
  gear1: 'Digit1',
  gear2: 'Digit2',
  gear3: 'Digit3',
  gear4: 'Digit4',
  gear5: 'Digit5',
  gear6: 'Digit6',
};

export const DEFAULT_SETTINGS: GameSettings = {
  controlType: 'wheel',
  transmission: 'automatic',
  wheelSensitivity: 1.0,
  gyroSensitivity: 1.0,
  masterVolume: 0.8,
  sfxVolume: 0.85,
  engineVolume: 0.75,
  showMinimap: true,
  shadows: true,
  keybindings: DEFAULT_KEYBINDINGS,
};

export const VEHICLES: VehicleConfig[] = [
  {
    id: 'compact-cruiser',
    name: 'Falcon Cruiser',
    brand: 'Urban Motors',
    category: 'Compact',
    description: 'Compact hatchback with agile steering lock. Perfect for tight parallel parking and beginners.',
    color: '#0284c7', // Sky Blue
    accentColor: '#0f172a',
    price: 0,
    unlocked: true,
    specs: {
      topSpeedKmh: 120,
      acceleration: 6.5,
      braking: 8.0,
      steeringLockDeg: 38,
      wheelbase: 2.4,
      width: 1.8,
      length: 3.9,
      height: 1.45,
      weightKg: 1150,
    },
  },
  {
    id: 'sport-coupe',
    name: 'Apex GT Coupe',
    brand: 'Veloce',
    category: 'Coupe',
    description: 'Rear-wheel-drive sports coupe with punchy torque and sharp steering precision.',
    color: '#dc2626', // Racing Red
    accentColor: '#1e293b',
    price: 1500,
    unlocked: true,
    specs: {
      topSpeedKmh: 190,
      acceleration: 8.8,
      braking: 8.5,
      steeringLockDeg: 35,
      wheelbase: 2.65,
      width: 1.9,
      length: 4.4,
      height: 1.35,
      weightKg: 1380,
    },
  },
  {
    id: 'luxury-suv',
    name: 'Titan 4x4',
    brand: 'Nordic Peak',
    category: 'SUV',
    description: 'Spacious luxury SUV. Demands careful wheel placement and wider turning arcs.',
    color: '#475569', // Slate Gunmetal
    accentColor: '#0f172a',
    price: 3000,
    unlocked: false,
    specs: {
      topSpeedKmh: 160,
      acceleration: 7.2,
      braking: 7.5,
      steeringLockDeg: 32,
      wheelbase: 2.9,
      width: 2.1,
      length: 4.85,
      height: 1.75,
      weightKg: 2100,
    },
  },
  {
    id: 'hyper-phantom',
    name: 'Phantom V12',
    brand: 'Aero Dynamics',
    category: 'Supercar',
    description: 'Exotic mid-engine supercar. Ultra low ground clearance, intense throttle, and carbon brakes.',
    color: '#eab308', // Racing Yellow
    accentColor: '#18181b',
    price: 6000,
    unlocked: false,
    specs: {
      topSpeedKmh: 240,
      acceleration: 9.6,
      braking: 9.5,
      steeringLockDeg: 34,
      wheelbase: 2.7,
      width: 2.05,
      length: 4.6,
      height: 1.2,
      weightKg: 1250,
    },
  },
];

export const LEVELS: LevelConfig[] = [
  {
    id: 1,
    title: 'Level 1: Forward Bay Basics',
    subtitle: 'Natijaviy to‘g‘ri bayga kirish (Straight Forward Bay)',
    difficulty: 'Easy',
    parTimeSeconds: 40,
    environment: 'day',
    playerStart: {
      x: 0,
      z: -25,
      rotation: 0, // facing positive Z
    },
    parkingTarget: {
      x: 0,
      z: 14,
      width: 2.8,
      length: 5.5,
      rotation: 0,
    },
    obstacles: [
      { id: 'c1', type: 'cone', x: -3.5, z: 10 },
      { id: 'c2', type: 'cone', x: 3.5, z: 10 },
      { id: 'c3', type: 'cone', x: -3.5, z: 17 },
      { id: 'c4', type: 'cone', x: 3.5, z: 17 },
      { id: 'b1', type: 'barrier', x: -6, z: 14, rotation: Math.PI / 2, width: 0.6, length: 7 },
      { id: 'b2', type: 'barrier', x: 6, z: 14, rotation: Math.PI / 2, width: 0.6, length: 7 },
      { id: 'pc1', type: 'parked_car', x: -9, z: 14, rotation: 0, color: '#334155' },
      { id: 'pc2', type: 'parked_car', x: 9, z: 14, rotation: 0, color: '#64748b' },
    ],
    boundary: { minX: -20, maxX: 20, minZ: -35, maxZ: 30 },
  },
  {
    id: 2,
    title: 'Level 2: Reverse Bay Maneuver',
    subtitle: 'Orqaga harakatlanib to‘xtash (Reverse Parking)',
    difficulty: 'Medium',
    parTimeSeconds: 50,
    environment: 'day',
    playerStart: {
      x: 8,
      z: 5,
      rotation: -Math.PI / 2, // facing -X
    },
    parkingTarget: {
      x: -6,
      z: 18,
      width: 2.8,
      length: 5.5,
      rotation: 0,
      reverseParkingPreferred: true,
    },
    obstacles: [
      { id: 'c1', type: 'cone', x: -3.8, z: 13 },
      { id: 'c2', type: 'cone', x: -8.2, z: 13 },
      { id: 'pc1', type: 'parked_car', x: -10, z: 18, rotation: 0, color: '#0f766e' },
      { id: 'pc2', type: 'parked_car', x: -2, z: 18, rotation: 0, color: '#b91c1c' },
      { id: 'b1', type: 'barrier', x: -6, z: 22, rotation: 0, width: 0.6, length: 5 },
      { id: 'b2', type: 'barrier', x: 12, z: 10, rotation: Math.PI / 2, width: 0.6, length: 14 },
    ],
    boundary: { minX: -22, maxX: 22, minZ: -15, maxZ: 30 },
  },
  {
    id: 3,
    title: 'Level 3: Tight Parallel Street',
    subtitle: 'Mashinalar o‘rtasiga parallel qo‘yish (Parallel Parking)',
    difficulty: 'Hard',
    parTimeSeconds: 65,
    environment: 'sunset',
    playerStart: {
      x: -5,
      z: -18,
      rotation: 0,
    },
    parkingTarget: {
      x: 4.5,
      z: 2,
      width: 2.7,
      length: 6.2,
      rotation: 0,
    },
    obstacles: [
      { id: 'pc_front', type: 'parked_car', x: 4.5, z: 9, rotation: 0, color: '#1e293b' },
      { id: 'pc_back', type: 'parked_car', x: 4.5, z: -5, rotation: 0, color: '#047857' },
      { id: 'curb_r', type: 'barrier', x: 6.5, z: 2, rotation: Math.PI / 2, width: 0.4, length: 30 },
      { id: 'curb_l', type: 'barrier', x: -9.5, z: 2, rotation: Math.PI / 2, width: 0.4, length: 30 },
      { id: 'c1', type: 'cone', x: 4.5, z: 5.6 },
      { id: 'c2', type: 'cone', x: 4.5, z: -1.6 },
    ],
    boundary: { minX: -15, maxX: 15, minZ: -25, maxZ: 25 },
  },
  {
    id: 4,
    title: 'Level 4: Slalom & Angle Parking',
    subtitle: 'Konuslar aylanmasi va burchakli joylashuv',
    difficulty: 'Medium',
    parTimeSeconds: 55,
    environment: 'day',
    playerStart: {
      x: -12,
      z: -24,
      rotation: 0,
    },
    parkingTarget: {
      x: 10,
      z: 16,
      width: 2.8,
      length: 5.6,
      rotation: -Math.PI / 4, // 45 degree angle parking!
    },
    obstacles: [
      { id: 'slalom1', type: 'cone', x: -12, z: -10 },
      { id: 'slalom2', type: 'cone', x: -6, z: -2 },
      { id: 'slalom3', type: 'cone', x: 0, z: 6 },
      { id: 'slalom4', type: 'cone', x: 6, z: 12 },
      { id: 'p1', type: 'pillar', x: -3, z: -15, width: 1.5, length: 1.5 },
      { id: 'p2', type: 'pillar', x: 5, z: -5, width: 1.5, length: 1.5 },
      { id: 'pc_adj', type: 'parked_car', x: 14.5, z: 12, rotation: -Math.PI / 4, color: '#4338ca' },
    ],
    boundary: { minX: -22, maxX: 22, minZ: -32, maxZ: 28 },
  },
  {
    id: 5,
    title: 'Level 5: Underground Pillar Bay',
    subtitle: 'Ustunlar orasida 90° aniq burilish',
    difficulty: 'Hard',
    parTimeSeconds: 70,
    environment: 'underground',
    playerStart: {
      x: -15,
      z: 0,
      rotation: Math.PI / 2, // facing +X
    },
    parkingTarget: {
      x: 10,
      z: -14,
      width: 2.7,
      length: 5.4,
      rotation: Math.PI / 2, // 90 deg bay
    },
    obstacles: [
      { id: 'col1', type: 'pillar', x: 7, z: -10.5, width: 1.4, length: 1.4 },
      { id: 'col2', type: 'pillar', x: 7, z: -17.5, width: 1.4, length: 1.4 },
      { id: 'col3', type: 'pillar', x: -3, z: -8, width: 1.4, length: 1.4 },
      { id: 'col4', type: 'pillar', x: -3, z: 8, width: 1.4, length: 1.4 },
      { id: 'pc1', type: 'parked_car', x: 10, z: -6.5, rotation: Math.PI / 2, color: '#e11d48' },
      { id: 'pc2', type: 'parked_car', x: 10, z: -21.5, rotation: Math.PI / 2, color: '#ca8a04' },
      { id: 'wall_back', type: 'barrier', x: 14, z: -14, rotation: Math.PI / 2, width: 0.6, length: 22 },
    ],
    boundary: { minX: -25, maxX: 22, minZ: -28, maxZ: 22 },
  },
  {
    id: 6,
    title: 'Level 6: Night Master Academy',
    subtitle: 'Tungi chiroqlar bilan tor hududda professional to‘xtash',
    difficulty: 'Expert',
    parTimeSeconds: 80,
    environment: 'night',
    playerStart: {
      x: 0,
      z: -28,
      rotation: 0,
    },
    parkingTarget: {
      x: -8,
      z: 16,
      width: 2.6,
      length: 5.4,
      rotation: Math.PI / 6,
    },
    obstacles: [
      { id: 'cone_night1', type: 'cone', x: -2, z: -10 },
      { id: 'cone_night2', type: 'cone', x: 2, z: -2 },
      { id: 'cone_night3', type: 'cone', x: -5, z: 8 },
      { id: 'pc_night1', type: 'parked_car', x: -12.5, z: 14, rotation: Math.PI / 6, color: '#475569' },
      { id: 'pc_night2', type: 'parked_car', x: -3.5, z: 18, rotation: Math.PI / 6, color: '#0284c7' },
      { id: 'barrier_n1', type: 'barrier', x: -8, z: 22, rotation: 0, width: 0.6, length: 10 },
      { id: 'barrier_n2', type: 'barrier', x: 10, z: 5, rotation: Math.PI / 2, width: 0.6, length: 24 },
    ],
    boundary: { minX: -24, maxX: 24, minZ: -35, maxZ: 30 },
  },
];
